// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: grpcfiledemo.proto
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#ifndef GRPC_grpcfiledemo_2eproto__INCLUDED
#define GRPC_grpcfiledemo_2eproto__INCLUDED

#include "grpcfiledemo.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace grpcfiledemo {

// Interface exported by the server.
class RouteGuide final {
 public:
  static constexpr char const* service_full_name() {
    return "grpcfiledemo.RouteGuide";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> FileExchange(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(FileExchangeRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> AsyncFileExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(AsyncFileExchangeRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> PrepareAsyncFileExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(PrepareAsyncFileExchangeRaw(context, cq));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* FileExchangeRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* AsyncFileExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* PrepareAsyncFileExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> FileExchange(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(FileExchangeRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> AsyncFileExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(AsyncFileExchangeRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>> PrepareAsyncFileExchange(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>>(PrepareAsyncFileExchangeRaw(context, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* FileExchangeRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* AsyncFileExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* PrepareAsyncFileExchangeRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FileExchange_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FileExchange(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_FileExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_FileExchange() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FileExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExchange(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFileExchange(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FileExchange<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_FileExchange : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_FileExchange() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FileExchange() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FileExchange(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::grpcfiledemo::Content, ::grpcfiledemo::Content>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace grpcfiledemo


#endif  // GRPC_grpcfiledemo_2eproto__INCLUDED
